CREATE TABLE IF NOT EXISTS users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    CONSTRAINT users_email_uk UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    available   BOOLEAN NOT NULL DEFAULT true,
    owner_id    BIGINT NOT NULL,
    CONSTRAINT items_owner_id_fk FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
   id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   item_id    BIGINT NOT NULL,
   booker_id  BIGINT NOT NULL,
   start_date TIMESTAMP NOT NULL,
   end_date   TIMESTAMP NOT NULL,
   status     VARCHAR(20) NOT NULL,
   CONSTRAINT bookings_item_id_fk   FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
   CONSTRAINT bookings_booker_id_fk   FOREIGN KEY (booker_id) REFERENCES users(id) ON DELETE CASCADE,
   CONSTRAINT bookings_dates_check  CHECK (start_date >= CURRENT_TIMESTAMP AND end_date > start_date),
   CONSTRAINT bookings_status_check CHECK (status IN ('APPROVED', 'REJECTED', 'WAITING'))
);

CREATE TABLE IF NOT EXISTS comments (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      VARCHAR(500) NOT NULL,
    item_id   BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT comments_item_id_fk         FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT comments_author_id_fk       FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT comments_unique_author_item UNIQUE (author_id, item_id)
);

-- TODO think about indexes