CREATE TABLE IF NOT EXISTS users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    CONSTRAINT users_email_uk UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    available   BOOLEAN NOT NULL DEFAULT true,
    user_id     BIGINT NOT NULL,
    CONSTRAINT items_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS bookings (
   id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   item_id    BIGINT NOT NULL,
   user_id    BIGINT NOT NULL,
   start_date TIMESTAMP NOT NULL,
   end_date   TIMESTAMP NOT NULL,
   status     VARCHAR(20) NOT NULL,
   CONSTRAINT bookings_item_id_fk   FOREIGN KEY (item_id) REFERENCES items(id),
   CONSTRAINT bookings_user_id_fk   FOREIGN KEY (user_id) REFERENCES users(id),
   CONSTRAINT bookings_dates_check  CHECK (start_date >= CURRENT_TIMESTAMP AND end_date > start_date),
   CONSTRAINT bookings_status_check CHECK (status IN ('APPROVED', 'REJECTED', 'WAITING'))
);

-- TODO think about indexes