CREATE TABLE IF NOT EXISTS users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    CONSTRAINT users_pk       PRIMARY KEY (id),
    CONSTRAINT users_email_uk UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    available   BOOLEAN NOT NULL DEFAULT true,
    user_id     BIGINT NOT NULL,
    CONSTRAINT items_pk PRIMARY KEY (id),
    CONSTRAINT items_user_id_fk FOREIGN KEY (user_id) REFERENCES users(id)
);

-- TODO think about indexes